CREATE TRIGGER IF NOT EXISTS PERSON_INSERT
    AFTER INSERT
    ON PEOPLE
BEGIN
    INSERT INTO
        USERS (PERSON_ID, USERNAME, PASSWORD, CREATED_DATE, LAST_MODIFIED_DATE)
    VALUES
        (
            (SELECT PERSON_ID FROM PEOPLE WHERE PERSON_ID = NEW.PERSON_ID),
            (SELECT LOWER((SUBSTR(FIRST_NAME, 0, 2) || MIDDLE_INITIAL || SUBSTR(LAST_NAME, 0, 7))) FROM PEOPLE WHERE PERSON_ID = NEW.PERSON_ID),
            'Password1',
            CURRENT_DATE,
            CURRENT_DATE
        );

    UPDATE 
        PEOPLE
    SET
        FULL_NAME = FIRST_NAME || ' ' || LAST_NAME,
        CREATED_DATE = CURRENT_DATE,
        LAST_MODIFIED_DATE = CURRENT_DATE
    WHERE
        PERSON_ID = NEW.PERSON_ID;
END;

CREATE TRIGGER IF NOT EXISTS LIST_HEADER_INSERT
    AFTER INSERT
    ON LIST_HEADERS
BEGIN
    UPDATE
        LIST_HEADERS
    SET
        CREATED_DATE = CURRENT_DATE,
        LAST_MODIFIED_DATE = CURRENT_DATE
    WHERE
        HEADER_ID = NEW.HEADER_ID;
END;

CREATE TRIGGER IF NOT EXISTS LIST_LINES_INSERT
    AFTER INSERT
    ON LIST_LINES
BEGIN
    UPDATE
        LIST_LINES
    SET
        CREATED_DATE = CURRENT_DATE,
        LAST_MODIFIED_DATE = CURRENT_DATE;
END;

CREATE TRIGGER IF NOT EXISTS ITEM_INSERT
    AFTER INSERT
    ON ITEMS
BEGIN
    UPDATE
        ITEMS
    SET
        CREATED_DATE = CURRENT_DATE,
        LAST_MODIFIED_DATE = CURRENT_DATE;
END;

CREATE TRIGGER IF NOT EXISTS PERSON_UPDATE
    AFTER UPDATE
    ON PEOPLE
BEGIN
    UPDATE
        PEOPLE
    SET
        LAST_MODIFIED_DATE = CURRENT_DATE
    WHERE
        PERSON_ID = NEW.PERSON_ID AND LAST_MODIFIED_DATE != CURRENT_DATE;
END;